/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./components/common/ColorPicker.vue')['default']
    CreateTodoDialog: typeof import('./components/todo/CreateTodoDialog.vue')['default']
    DesktopHeader: typeof import('./components/layout/desktop/DesktopHeader.vue')['default']
    DesktopMainLayout: typeof import('./components/layout/desktop/DesktopMainLayout.vue')['default']
    DesktopSidebar: typeof import('./components/layout/desktop/DesktopSidebar.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GroupManageDialog: typeof import('./components/group/GroupManageDialog.vue')['default']
    IconPicker: typeof import('./components/common/IconPicker.vue')['default']
    Logo: typeof import('./components/icon/logo.vue')['default']
    MobileDrawer: typeof import('./components/layout/mobile/MobileDrawer.vue')['default']
    MobileMainLayout: typeof import('./components/layout/mobile/MobileMainLayout.vue')['default']
    MobileNav: typeof import('./components/layout/mobile/MobileNav.vue')['default']
    MobileTopBar: typeof import('./components/layout/mobile/MobileTopBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagCreateDialog: typeof import('./components/tag/TagCreateDialog.vue')['default']
    TagManageDialog: typeof import('./components/tag/TagManageDialog.vue')['default']
    TodoDetailPanel: typeof import('./components/todo/TodoDetailPanel.vue')['default']
  }
}
